name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t abhishekmishra6121/node-docker-app:latest .
        docker push abhishekmishra6121/node-docker-app:latest

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.203.159.115 <<EOF
        docker pull abhishekmishra6121/node-docker-app:latest
        docker stop node-app || true
        docker rm node-app || true
        docker run -d --name node-app -p 80:3000 abhishekmishra6121/node-docker-app:latest
        EOF
