name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3 

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t abhishekmishra6121/node-docker-app:latest .
        docker push abhishekmishra6121/node-docker-app:latest

    # Step 4: Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        # Save the private key to a file and set the correct permissions
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > key.pem
        chmod 600 key.pem

        # Connect to the EC2 instance and deploy the Docker container
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@13.203.40.10 <<EOF
        docker pull abhishekmishra6121/node-docker-app:latest
        docker stop node-app || true
        docker rm node-app || true
        docker run -d --name node-app -p 80:3000 abhishekmishra6121/node-docker-app:latest
        EOF
